
var LinrockNnue7Web = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

function aa(){f.buffer!=k.buffer&&m();return k}function p(){f.buffer!=k.buffer&&m();return ba}function r(){f.buffer!=k.buffer&&m();return ca}function t(){f.buffer!=k.buffer&&m();return da}function ea(){f.buffer!=k.buffer&&m();return fa}var u=moduleArg,ha,v;u.ready=new Promise((a,b)=>{ha=a;v=b});u.listen||(u.listen=a=>console.log(a));u.onError||(u.onError=a=>console.error(a));u.print=a=>u.listen?.(a);u.printErr=a=>u.onError?.(a);u.getRecommendedNnue=()=>x(ia());
u.postMessage=function(a){const b=ja(a)+1,c=ka(b);if(!c)throw Error(`Could not allocate ${b} bytes`);la(a,c,b);ma(c)};u.setNnueBuffer=function(a){if(a){if(0>=a.byteLength)throw Error(`${a.byteLength} bytes?`);var b=ka(a.byteLength);if(!b)throw Error(`Could not allocate ${a.byteLength} bytes`);u.HEAPU8.set(a,b);na(b,a.byteLength)}else na(0,0)};
var oa=Object.assign({},u),pa="object"==typeof window,z="function"==typeof importScripts,qa="object"==typeof process&&"object"==typeof process.ua&&"string"==typeof process.ua.node,B=u.ENVIRONMENT_IS_PTHREAD||!1,C="";function ra(a){return u.locateFile?u.locateFile(a,C):C+a}var sa;
if(pa||z)z?C=self.location.href:"undefined"!=typeof document&&document.currentScript&&(C=document.currentScript.src),_scriptDir&&(C=_scriptDir),0!==C.indexOf("blob:")?C=C.substr(0,C.replace(/[?#].*/,"").lastIndexOf("/")+1):C="",z&&(sa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ta=u.print||console.log.bind(console),D=u.printErr||console.error.bind(console);Object.assign(u,oa);oa=null;var noExitRuntime=!1;
"object"!=typeof WebAssembly&&F("no native wasm support detected");var f,ua,G=!1,H,k,ba,ca,da,fa;function m(){var a=f.buffer;u.HEAP8=k=new Int8Array(a);u.HEAP16=new Int16Array(a);u.HEAPU8=ba=new Uint8Array(a);u.HEAPU16=new Uint16Array(a);u.HEAP32=ca=new Int32Array(a);u.HEAPU32=da=new Uint32Array(a);u.HEAPF32=new Float32Array(a);u.HEAPF64=fa=new Float64Array(a)}var I=67108864;2097152<=I||F("INITIAL_MEMORY should be larger than STACK_SIZE, was "+I+"! (STACK_SIZE=2097152)");
if(B)f=u.wasmMemory;else if(u.wasmMemory)f=u.wasmMemory;else if(f=new WebAssembly.Memory({initial:I/65536,maximum:32768,shared:!0}),!(f.buffer instanceof SharedArrayBuffer))throw D("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),qa&&D("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");m();I=f.buffer.byteLength;var va=[],wa=[],xa=[],ya=[],za=[],Aa=!1,J=0;function K(){return noExitRuntime||0<J}var M=0,Ba=null,N=null;function Ca(){M--;if(0==M&&(null!==Ba&&(clearInterval(Ba),Ba=null),N)){var a=N;N=null;a()}}function F(a){a="Aborted("+a+")";D(a);G=!0;H=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");v(a);throw a;}function Da(a){return a.startsWith("data:application/octet-stream;base64,")}var O;
u.locateFile?(O="linrock-nnue-7.wasm",Da(O)||(O=ra(O))):O=(new URL("linrock-nnue-7.wasm",import.meta.url)).href;function Ea(a){if(sa)return sa(a);throw"both async and sync fetching of the wasm failed";}function Fa(a){return(pa||z)&&"function"==typeof fetch?fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a)):Promise.resolve().then(()=>Ea(a))}
function Ga(a,b,c){return Fa(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(c,e=>{D(`failed to asynchronously prepare wasm: ${e}`);F(e)})}function Ha(a,b){var c=O;return"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(h){D(`wasm streaming compile failed: ${h}`);D("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
function Ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ja=a=>{a.terminate();a.onmessage=()=>{}},La=a=>{0==P.Y.length&&(Ka(),P.fa(P.Y[0]));var b=P.Y.pop();if(!b)return 6;P.$.push(b);P.W[a.Z]=b;b.Z=a.Z;b.postMessage({cmd:"run",start_routine:a.oa,arg:a.la,pthread_ptr:a.Z},a.ta);return 0},Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Na=(a,b,c)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(e="";b<c;){var h=a[b++];if(h&128){var g=
a[b++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|g);else{var l=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|l:(h&7)<<18|g<<12|l<<6|a[b++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e},x=(a,b)=>a?Na(p(),a,b):"";function Oa(a){if(B)return Q(0,1,a);H=a;K()||(P.ia(),G=!0);throw new Ia(a);}
var S=a=>{H=a;if(B)throw Pa(a),"unwind";K()||B||(Qa(),R(ya),Ra(0),Sa[1].length&&Ta(1,10),Sa[2].length&&Ta(2,10),P.ia(),Aa=!0);Oa(a)},Ua=a=>{if(!(a instanceof Ia||"unwind"==a))throw a;};function Va(){for(var a=navigator.hardwareConcurrency;a--;)Ka();va.unshift(()=>{M++;Wa(()=>Ca())})}function Ka(){if(u.locateFile){var a=ra("linrock-nnue-7.worker.js");a=new Worker(a)}else a=new Worker(new URL("linrock-nnue-7.worker.js",import.meta.url));P.Y.push(a)}
function Wa(a){B?a():Promise.all(P.Y.map(P.fa)).then(a)}
var P={Y:[],$:[],ka:[],W:{},ha:a=>{H=a},xa:["$terminateWorker"],ia:()=>{for(var a of P.$)Ja(a);for(a of P.Y)Ja(a);P.Y=[];P.$=[];P.W=[]},ga:a=>{var b=a.Z;delete P.W[b];P.Y.push(a);P.$.splice(P.$.indexOf(a),1);a.Z=0;Xa(b)},na(){},ja(){P.ka.forEach(a=>a())},fa:a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var l=g.cmd;if(g.targetThread&&g.targetThread!=T()){var w=P.W[g.targetThread];w?w.postMessage(g,g.transferList):D(`Internal error! Worker sent a message "${l}" to target pthread ${g.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===l)U();
else if("spawnThread"===l)La(g);else if("cleanupThread"===l)(g=P.W[g.thread])||F(),P.ga(g);else if("killThread"===l)g=g.thread,l=P.W[g],delete P.W[g],Ja(l),Xa(g),P.$.splice(P.$.indexOf(l),1),l.Z=0;else if("cancelThread"===l)P.W[g.thread].postMessage({cmd:"cancel"});else if("loaded"===l)a.loaded=!0,b(a);else if("alert"===l)alert(`Thread ${g.threadId}: ${g.text}`);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===l)u[g.handler](...g.args);else l&&D(`worker sent an unknown command ${l}`)};
a.onerror=g=>{D(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};var c=[],e=["print","printErr"],h;for(h of e)u.hasOwnProperty(h)&&c.push(h);a.postMessage({cmd:"load",handlers:c,urlOrBlob:u.mainScriptUrlOrBlob,wasmMemory:f,wasmModule:ua})})};u.PThread=P;var R=a=>{for(;0<a.length;)a.shift()(u)};u.establishStackSpace=()=>{var a=T(),b=t()[a+52>>2];a=t()[a+56>>2];Ya(b,b-a);Za(b)};function Pa(a){if(B)return Q(1,0,a);--J;S(a)}var V=[],$a;
u.invokeEntryPoint=(a,b)=>{J=0;var c=V[a];c||(a>=V.length&&(V.length=a+1),V[a]=c=$a.get(a));a=c(b);K()?P.ha(a):ab(a)};function bb(a,b,c,e){return B?Q(2,1,a,b,c,e):cb(a,b,c,e)}var cb=(a,b,c,e)=>{if("undefined"==typeof SharedArrayBuffer)return D("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var h=[];if(B&&0===h.length)return bb(a,b,c,e);a={oa:c,Z:a,la:e,ta:h};return B?(a.wa="spawnThread",postMessage(a,h),0):La(a)};
function db(a,b,c){return B?Q(3,1,a,b,c):0}function eb(a,b,c){return B?Q(4,1,a,b,c):0}function fb(a,b,c,e){if(B)return Q(5,1,a,b,c,e)}var gb=a=>{if(!Aa&&!G)try{if(a(),!Aa&&!K())try{B?ab(H):S(H)}catch(b){Ua(b)}}catch(b){Ua(b)}},hb=a=>{"function"===typeof Atomics.va&&(Atomics.va(r(),a>>2,a).value.then(U),a+=128,Atomics.store(r(),a>>2,1))};u.__emscripten_thread_mailbox_await=hb;var U=()=>{var a=T();a&&(hb(a),gb(()=>ib()))};u.checkMailbox=U;var kb=a=>{var b=jb();a=a();Za(b);return a};
function Q(a,b){var c=arguments.length-2,e=arguments;return kb(()=>{for(var h=lb(8*c),g=h>>3,l=0;l<c;l++){var w=e[2+l];ea()[g+l]=w}return mb(a,c,h,b)})}
var nb=[],W,ob={},tb=()=>{if(!sb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in ob)void 0===ob[b]?delete a[b]:a[b]=ob[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);sb=c}return sb},sb;
function ub(a,b){if(B)return Q(6,1,a,b);var c=0;tb().forEach((e,h)=>{var g=b+c;h=t()[a+4*h>>2]=g;for(g=0;g<e.length;++g)aa()[h++>>0]=e.charCodeAt(g);aa()[h>>0]=0;c+=e.length+1});return 0}function vb(a,b){if(B)return Q(7,1,a,b);var c=tb();t()[a>>2]=c.length;var e=0;c.forEach(h=>e+=h.length+1);t()[b>>2]=e;return 0}function wb(a){return B?Q(8,1,a):52}function xb(a,b,c,e){return B?Q(9,1,a,b,c,e):52}function yb(a,b,c,e,h){return B?Q(10,1,a,b,c,e,h):70}
var Sa=[null,[],[]],Ta=(a,b)=>{var c=Sa[a];0===b||10===b?((1===a?ta:D)(Na(c,0)),c.length=0):c.push(b)};function zb(a,b,c,e){if(B)return Q(11,1,a,b,c,e);for(var h=0,g=0;g<c;g++){var l=t()[b>>2],w=t()[b+4>>2];b+=8;for(var L=0;L<w;L++)Ta(a,p()[l+L]);h+=w}t()[e>>2]=h;return 0}
var X=a=>0===a%4&&(0!==a%100||0===a%400),Ab=[31,29,31,30,31,30,31,31,30,31,30,31],Bb=[31,28,31,30,31,30,31,31,30,31,30,31],ja=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},Cb=(a,b,c,e)=>{if(!(0<e))return 0;var h=c;e=c+e-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var w=a.charCodeAt(++g);l=65536+((l&1023)<<10)|w&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=
192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-h};function Db(a){var b=Array(ja(a)+1);Cb(a,b,0,b.length);return b}
var Eb=(a,b)=>{aa().set(a,b)},Fb=(a,b,c,e)=>{function h(d,n,q){for(d="number"==typeof d?d.toString():d||"";d.length<n;)d=q[0]+d;return d}function g(d,n){return h(d,n,"0")}function l(d,n){function q(pb){return 0>pb?-1:0<pb?1:0}var E;0===(E=q(d.getFullYear()-n.getFullYear()))&&0===(E=q(d.getMonth()-n.getMonth()))&&(E=q(d.getDate()-n.getDate()));return E}function w(d){switch(d.getDay()){case 0:return new Date(d.getFullYear()-1,11,29);case 1:return d;case 2:return new Date(d.getFullYear(),0,3);case 3:return new Date(d.getFullYear(),
0,2);case 4:return new Date(d.getFullYear(),0,1);case 5:return new Date(d.getFullYear()-1,11,31);case 6:return new Date(d.getFullYear()-1,11,30)}}function L(d){var n=d.aa;for(d=new Date((new Date(d.ba+1900,0,1)).getTime());0<n;){var q=d.getMonth(),E=(X(d.getFullYear())?Ab:Bb)[q];if(n>E-d.getDate())n-=E-d.getDate()+1,d.setDate(1),11>q?d.setMonth(q+1):(d.setMonth(0),d.setFullYear(d.getFullYear()+1));else{d.setDate(d.getDate()+n);break}}q=new Date(d.getFullYear()+1,0,4);n=w(new Date(d.getFullYear(),
0,4));q=w(q);return 0>=l(n,d)?0>=l(q,d)?d.getFullYear()+1:d.getFullYear():d.getFullYear()-1}var A=t()[e+40>>2];e={ra:r()[e>>2],qa:r()[e+4>>2],ca:r()[e+8>>2],ea:r()[e+12>>2],da:r()[e+16>>2],ba:r()[e+20>>2],X:r()[e+24>>2],aa:r()[e+28>>2],ya:r()[e+32>>2],pa:r()[e+36>>2],sa:A?x(A):""};c=x(c);A={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in A)c=c.replace(new RegExp(y,"g"),A[y]);var qb="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),rb="January February March April May June July August September October November December".split(" ");A={"%a":d=>qb[d.X].substring(0,3),"%A":d=>qb[d.X],"%b":d=>rb[d.da].substring(0,3),"%B":d=>rb[d.da],"%C":d=>g((d.ba+1900)/
100|0,2),"%d":d=>g(d.ea,2),"%e":d=>h(d.ea,2," "),"%g":d=>L(d).toString().substring(2),"%G":d=>L(d),"%H":d=>g(d.ca,2),"%I":d=>{d=d.ca;0==d?d=12:12<d&&(d-=12);return g(d,2)},"%j":d=>{for(var n=0,q=0;q<=d.da-1;n+=(X(d.ba+1900)?Ab:Bb)[q++]);return g(d.ea+n,3)},"%m":d=>g(d.da+1,2),"%M":d=>g(d.qa,2),"%n":()=>"\n","%p":d=>0<=d.ca&&12>d.ca?"AM":"PM","%S":d=>g(d.ra,2),"%t":()=>"\t","%u":d=>d.X||7,"%U":d=>g(Math.floor((d.aa+7-d.X)/7),2),"%V":d=>{var n=Math.floor((d.aa+7-(d.X+6)%7)/7);2>=(d.X+371-d.aa-2)%7&&
n++;if(n)53==n&&(q=(d.X+371-d.aa)%7,4==q||3==q&&X(d.ba)||(n=1));else{n=52;var q=(d.X+7-d.aa-1)%7;(4==q||5==q&&X(d.ba%400-1))&&n++}return g(n,2)},"%w":d=>d.X,"%W":d=>g(Math.floor((d.aa+7-(d.X+6)%7)/7),2),"%y":d=>(d.ba+1900).toString().substring(2),"%Y":d=>d.ba+1900,"%z":d=>{d=d.pa;var n=0<=d;d=Math.abs(d)/60;return(n?"+":"-")+String("0000"+(d/60*100+d%60)).slice(-4)},"%Z":d=>d.sa,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(y in A)c.includes(y)&&(c=c.replace(new RegExp(y,"g"),A[y](e)));c=c.replace(/\0\0/g,
"%");y=Db(c);if(y.length>b)return 0;Eb(y,a);return y.length-1},la=(a,b,c)=>Cb(a,p(),b,c);B?(P.receiveObjectTransfer=P.na,P.threadInitTLS=P.ja,P.setExitStatus=P.ha,noExitRuntime=!1):Va();
var Gb=[Oa,Pa,bb,db,eb,fb,ub,vb,wb,xb,yb,zb],Ib={l:a=>{Hb(a,!z,1,!pa,2097152,!1);P.ja()},i:a=>{B?postMessage({cmd:"cleanupThread",thread:a}):((a=P.W[a])||F(),P.ga(a))},y:cb,h:db,t:eb,u:fb,z:()=>!0,x:(a,b)=>{a==b?setTimeout(()=>U()):B?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=P.W[a])&&a.postMessage({cmd:"checkMailbox"})},j:(a,b,c,e)=>{nb.length=c;e>>=3;for(var h=0;h<c;h++)nb[h]=ea()[e+h];a=Gb[a];P.ma=b;b=a.apply(null,nb);P.ma=0;return b},k:hb,g:()=>{},b:()=>{F("")},e:()=>{z||(W||(W={}),W["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(W["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,D("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")),F("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},m:()=>{J+=1;throw"unwind";},c:()=>performance.timeOrigin+performance.now(),
w:a=>{var b=p().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var h=Math;e=Math.max(a,e);a:{h=(h.min.call(h,2147483648,e+(65536-e%65536)%65536)-f.buffer.byteLength+65535)/65536;try{f.grow(h);m();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},n:()=>K(),q:ub,r:vb,d:S,f:wb,s:xb,o:yb,v:zb,a:f||u.wasmMemory,p:(a,b,c,e)=>Fb(a,b,c,e)},Y=function(){function a(c,e){Y=c.exports;P.ka.push(Y.F);$a=Y.I;wa.unshift(Y.A);ua=e;Ca();return Y}
var b={a:Ib};M++;if(u.instantiateWasm)try{return u.instantiateWasm(b,a)}catch(c){D(`Module.instantiateWasm callback failed with error: ${c}`),v(c)}Ha(b,function(c){a(c.instance,c.module)}).catch(v);return{}}();u.__Z10js_getlinev=a=>(u.__Z10js_getlinev=Y.B)(a);var ia=u._getRecommendedNnue=()=>(ia=u._getRecommendedNnue=Y.C)(),ma=u._uci=a=>(ma=u._uci=Y.D)(a),na=u._setNnueBuffer=(a,b)=>(na=u._setNnueBuffer=Y.E)(a,b);u.__emscripten_tls_init=()=>(u.__emscripten_tls_init=Y.F)();
var T=u._pthread_self=()=>(T=u._pthread_self=Y.G)(),Jb=u.__emscripten_proxy_main=(a,b)=>(Jb=u.__emscripten_proxy_main=Y.H)(a,b),Qa=()=>(Qa=Y.J)(),Hb=u.__emscripten_thread_init=(a,b,c,e,h,g)=>(Hb=u.__emscripten_thread_init=Y.K)(a,b,c,e,h,g);u.__emscripten_thread_crashed=()=>(u.__emscripten_thread_crashed=Y.L)();
var Ra=u._fflush=a=>(Ra=u._fflush=Y.M)(a),ka=u._malloc=a=>(ka=u._malloc=Y.N)(a),mb=(a,b,c,e)=>(mb=Y.O)(a,b,c,e),Xa=a=>(Xa=Y.P)(a),ab=u.__emscripten_thread_exit=a=>(ab=u.__emscripten_thread_exit=Y.Q)(a),ib=u.__emscripten_check_mailbox=()=>(ib=u.__emscripten_check_mailbox=Y.R)(),Ya=(a,b)=>(Ya=Y.S)(a,b),jb=()=>(jb=Y.T)(),Za=a=>(Za=Y.U)(a),lb=a=>(lb=Y.V)(a);u.keepRuntimeAlive=K;u.wasmMemory=f;u.UTF8ToString=x;u.stringToUTF8=la;u.ExitStatus=Ia;var Z;N=function Kb(){Z||Lb();Z||(N=Kb)};
function Lb(){if(!(0<M))if(B)ha(u),B||R(wa),startWorker(u);else if(R(va),!(0<M||Z||(Z=!0,u.calledRun=!0,G))){B||R(wa);B||R(xa);ha(u);if(Mb){var a=Jb;J+=1;try{var b=a(0,0);S(b,!0)}catch(c){Ua(c)}}B||R(za)}}var Mb=!0;Lb();


  return moduleArg.ready
}

);
})();
export default LinrockNnue7Web;