name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "<major>.<minor>.<patch>"
        required: true
      description:
        description: "Release description"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Verify Emscripten
        run: emcc --version

      - name: Build all stockfish variants
        run: ./build.py --flags='-O3 -DNDEBUG --closure=1' all

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Rev version in package.json and push version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version ${{ github.event.inputs.version }}
          git push origin HEAD
          git push origin v${{ github.event.inputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
          files: |
            ./sf16-7.js
            ./sf16-7.wasm
            ./sf171-79.js
            ./sf171-79.wasm
            ./fsf14.js
            ./fsf14.wasm
            ./package.json
            ./stockfishWeb.d.ts
            ./LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
