name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.3)"
        required: true
      description:
        description: "Description"
        required: false
        default: ""
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Validate version
        run: |
          [[ "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]] || \
          (echo "Version must start with 'v' and match 'v<major>.<minor>.<patch>'" && exit 1)

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup emscripten
        id: emscripten
        run: echo "VERSION=$(./build.py --emcc-version)" >> "$GITHUB_OUTPUT"

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ steps.emscripten.outputs.VERSION }}
      - run: emcc --version

      - name: Build stockfishes
        run: ./build.py all

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Bump package.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          NPM_VERSION="${GITHUB_VERSION#v}"
          npm version "$NPM_VERSION"
        env:
          GITHUB_VERSION: ${{ github.event.inputs.version }}

      - name: Publish to npm
        run: |
          npm publish --provenance --access public
          git push origin HEAD --follow-tags

      - name: Publish to github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
